### ISSUE TITLE
How do I align the text in centre? 

### ISSUE THREAD

**Issue by raghav4** [WinterCore/react-text-transition#10]
I'm using `mdbootstrap` when I'm trying to align the text to the centre, I cannot override it. 

Here's the link to the [sandbox](https://codesandbox.io/s/nifty-spence-lcw6s?file=/src/transitionText.jsx),

The text is aligned to the left. The `mdbootstrap`'s `text-align` class is not working with it.

**Comment by raghav4** [comment]
I've tried aligning the text using the custom styling, `style={{ textAlign: "centre !important" }}` but it didn't work too.

**Comment by WinterCore** [comment]
Yeah I know. I'm looking into it. Just give me some time 😉

**Comment by raghav4** [comment]
> Yeah I know. I'm looking into it. Just give me some time 😉

Justed wanted you to know! Thanks 😅

**Comment by WinterCore** [comment]
Hey @raghav4.

Normally you would just have to add the `inline` prop. but that didn't work because the text was being wrapped on multiple lines (the width calculation was always wrong).
So I just had to add `white-space: nowrap` to the container.

Here's an updated [codesandbox](https://codesandbox.io/s/cool-thunder-ikj5b?file=/src/transitionText.jsx) example.

Make to update to the latest version `1.1.0` and provide the `inline` prop.

Thanks for reporting this 😃.

**Comment by WinterCore** [comment]
Resolved in GH-11

**Comment by raghav4** [comment]
Thank you @WinterCore, it worked. Testing out some other things as well might report them too!

**Comment by raghav4** [comment]
@WinterCore is it possible to use this as a component to animate the `<textarea>{'Animate The text Inside'}</textarea>` ?

**Comment by raghav4** [comment]
@WinterCore, Sorry for interrupting again, it doesn't work for **paragraphs**. I tried it for **lorem ipsum placeholder text**, it should have given a responsive behaviour. 

<img width="338" alt="Screenshot 2020-05-09 at 7 54 54 PM" src="https://user-images.githubusercontent.com/20716185/81476308-f7194200-922e-11ea-9117-4f7f342d946f.png">

or doesn't it support paragraphs? 😅

**Comment by WinterCore** [comment]
Hey @raghav4.
> is it possible to use this as a component to animate the <textarea>{'Animate The text Inside'}</textarea>

I'm not sure that's possible. Maybe you can try this other package [react-text-loop](https://www.npmjs.com/package/react-text-loop)

> Sorry for interrupting again, it doesn't work for paragraphs. I tried it for lorem ipsum placeholder text, it should have given a responsive behaviour.

Have you tried removing the `inline` prop, the text should automatically break into multiple lines.

Let me know if you need anything else 😀.

**Comment by WinterCore** [comment]
> Have you tried removing the inline prop, the text should automatically break into multiple lines.

Sometimes changing props needs a full-page refresh in order to work. I'll work on fixing that soon.

**Comment by raghav4** [comment]
> > Have you tried removing the inline prop, the text should automatically break into multiple lines.
> 
> Sometimes changing props need a full-page refresh in order for it to work. I'll work on fixing that soon.

Yes, exactly as you say. Thank you! 😄
