### ISSUE TITLE
Heads Up for the example, add an empty array on the useEffect

### ISSUE THREAD

**Issue by e-nouri** [WinterCore/react-text-transition#19]
add  an empty array on the second argument for useEffect or it will keep running the effect and life will end (for your browser)

**Comment by WinterCore** [comment]
Hello.

I think what you're talking about is that when you switch to another browser tab, the animation doesn't stop, when you come back all the missed animations will be played (if not. please elaborate).
This is a known issue and has nothing to do with `useEffect`. All `useEffect` calls have their second argument populated.
Please correct me if I'm wrong.

Thanks.

**Comment by globalstripe** [comment]
Thanks e-nouri.

I changed useEffect to this to fix the problem (dont' think this is anything to do with changing tabs -  using the example code eventually crashes my page if i run it without adding the [null] !)

  React.useEffect(() => {
    const intervalId = setInterval(() =>
      setIndex(index => index + 1),
      3000 ) // every 3 seconds 
  },[null])
