### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by momocow** [WinterCore/react-text-transition#21]
Hi, I'm using this component in my Gatsby project and found it failed the SSR build since the distributable of this component is an UMD module which contains the `window` variable.

To fix the issue, I would suggest to [set `output.globalObject` to `this`](https://github.com/webpack/webpack/issues/6784#issuecomment-557449449) in the webpack config; or bring this project upgrading to webpack v5 which should fix this issue by default.

Thank you for a nice component!

Reference:
https://github.com/webpack/webpack/issues/6784

**Comment by WinterCore** [comment]
Hey.

Thanks for your suggestion to set `output.globalObject` to `this`.
While this did fix the issue you mentioned, it seems that there are other issues affecting SSR.
I started getting `document is not defined`. which apparently comes from `style-loader`.
I'll do some research and see what I can do.

Thanks for reporting this.

**Comment by WinterCore** [comment]
Hello. @momocow 

Gatsby's SSR build should be working now on the latest version of this component (1.1.4).

Let me know if you face any other issues.

Thanks again.

**Comment by doublejosh** [comment]
I believe SSR/Gatsby may cause a loading bug due to the absolutely positioned placeholder...


https://user-images.githubusercontent.com/205608/188792783-b70a9791-6171-43ab-9164-5671f2b975d5.mp4

**Comment by doublejosh** [comment]
I just needed to upgrade!
