### ISSUE TITLE
wont update width on visibility change

### ISSUE THREAD

**Issue by LucasKristandt** [WinterCore/react-text-transition#25]
When TextTransition is not visible on load and will be visible due to window resize it does not update its width and therefore stays invisible -> width: 0px;
<img width="359" alt="Bildschirmfoto 2021-02-26 um 14 00 38" src="https://user-images.githubusercontent.com/52002265/109303396-08255500-783b-11eb-95e8-fc658881fcde.png">

**Comment by WinterCore** [comment]
Hello there.

> When TextTransition is not visible on load and will be visible due to window resize

What do you mean exactly by that?
Is the TextTransition outside the viewport of the screen? and you have something like a parent with overflow hidden?

It would be great if you could reproduce it in a CodeSandBox example. cuz I have very little info to work with here.

Thanks.

**Comment by jvincent3** [comment]
I'm not sure if I have the same issue as him but my text-transition width is at auto, so basically it's just occupying the whole width of the parent box. 
Example: https://codesandbox.io/s/trusting-sun-35wmx?file=/src/App.js

The S on the code example is just staying at the bottom, if I use display: flex it fixes it a bit but it doesn't have that smooth slide effect.

**Comment by WinterCore** [comment]
Hey @jvincent3 

I think you want the width to be animated if I understood you correctly.
For that, you just have to pass the `inline` flag.
```ts
<TextTransition
    text={TEXTS[index % TEXTS.length]}
    springConfig={presets.wobbly}
    inline
/>
```
