### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by MihaiWill** [WinterCore/react-text-transition#26]
Hi, when i add this those styles, it not render at it should:
```
 style={{
          fontSize: "48px",
          fontWeight: "800",
          background: "-webkit-linear-gradient(45deg, #09009f, #00ff95 80%)",
          WebkitBackgroundClip: "text",
          WebkitTextFillColor: "transparent",
        }}
```

How can i render it the right way?

**Comment by WinterCore** [comment]
Hello there.

So the thing is that when you use the `style` prop the styles get applied to the outer container, but the CSS property `-webkit-background-clip` has to be applied directly to the element that contains the text for it to work.

[CodeSandBox Example](https://codesandbox.io/s/dawn-hooks-bsg95)

Let me know if you have any more questions.

**Comment by MihaiWill** [comment]
Awesome!! Thanks so much

**Comment by ezorfa** [comment]
Hi @WinterCore !

Could you please reshare the code sandbox as the link seems to be broken?
