### ISSUE TITLE
React 18 support?

### ISSUE THREAD

**Issue by Mozzius** [WinterCore/react-text-transition#45]
I think something breaks when trying to use with React 18 - the text still changes but there's no animation

**Comment by WinterCore** [comment]
Hey.

Yeah, unfortunately I've been a bit busy lately. I'll try to look into it as soon as I have some time.
Feel free to submit a PR if you're in a hurry.

Thanks

**Comment by Mozzius** [comment]
Had a look at fixing it myself but updating the React version locally worked without a hitch, so I don't really know what's going on.

Here's a codesandbox reproduction: [https://codesandbox.io/s/react-text-transition-react-18-demo-yy0vum](https://codesandbox.io/s/react-text-transition-react-18-demo-yy0vum)

**Comment by DonSmog** [comment]
> I think something breaks when trying to use with React 18 - the text still changes but there's no animation

I'm facing the same issue. There's transition but no animation. When I navigate away from the screen and return back, there's a split seconds animation. Thinking its a react 18 issue

**Comment by WinterCore** [comment]
Hey @Mozzius & @DonSmog 

This issue has been resolved in [v2.0.0](https://www.npmjs.com/package/react-text-transition/v/2.0.0), make sure you install the latest version.

Thanks for reporting this and sorry for the delay.
