### ISSUE TITLE
How to render a space

### ISSUE THREAD

**Issue by HugoMito** [WinterCore/react-text-transition#46]
Hi support team,

Could you guide me on how to render a space?
```
import ReactTextTransition from "react-text-transition";

{"Please, wait...".split("").map((character, index) => {
  return <ReactTextTransition
    className="loading"
    delay={index * 70}
    direction="up"
    inline
    key={index}
    noOverflow
    text={character} />
})}
```
The code above displays:  
### Please,wait...

Thanks for your support!

**Comment by ch3rn1k** [comment]
Well, this package ignores "empty" variable, so you can do a small trick by wrapping your space character with special symbol **[Word Joiner](https://unicode-table.com/en/2060/)**:

```
{"Please, wait...".split("").map((character, index) => {
    return <TextTransition
      className="loading"
      delay={index * 70}
      direction="up"
      inline
      key={index}
      noOverflow
      text={character === ' ' ? '⁠ ⁠' : character} />
  })}
```

**Comment by HugoMito** [comment]
Thanks a lot @ch3rn1k!
That trick worked perfectly fine.

I am closing this issue.
Regards,
