### ISSUE TITLE
Module not found error ! Not working with nextjs 13

### ISSUE THREAD

**Issue by Lekhrajk** [WinterCore/react-text-transition#57]
I just installed it and nextjs is throwing the following error

`./node_modules/react-text-transition/lib-esm/components/TextTransition.js:13:0
Module not found: Can't resolve 'prop-types'`

i am using 
    "next": "latest",
    "react": "18.2.0",
    "react-dom": "18.2.0",

any solution for this?

**Comment by stefandev15** [comment]
Running `npm i prop-types` should fix your problem!

**Comment by idindrakusuma** [comment]
Since this package use Typescript. I think no need to use prop-types again. I'm creating the PR for the fix
https://github.com/WinterCore/react-text-transition/pull/64

**Comment by idindrakusuma** [comment]
Hi @Lekhrajk 
This issue should be solved by updating to `v3.1.0`. 

I will close this issue, and feel free to re-open again if you still facing the issue. Thank you!

**Comment by Lekhrajk** [comment]
Ok will check. Thanks for your answer
