### ISSUE TITLE
"Ghost" Effect

### ISSUE THREAD

**Issue by PatryckSilva** [WinterCore/react-text-transition#62]
Hi, i wanna know how can i remove the "Ghost" effect in every transition. When the transition happens, a ghosting effect remains
![image](https://user-images.githubusercontent.com/41785386/222752172-97a791ea-8296-48c3-83ae-3cfe0de9d26d.png)

**Comment by Evoteam87** [comment]
Bos tanggung jwb nye mana,kok main kabur saja dari grup,,pamit kgk ada info kgk, kerja yg amanah,punya anak masih balita di kasih makan duit haram,masya allah... Sehat bos kabur dari tanggung jwb
