### ISSUE TITLE
Letters appear "stuck"

### ISSUE THREAD

**Issue by Lukewhite9** [WinterCore/react-text-transition#69]
I have used react-text-transition to animate single letters, so a word can appear to transform from one to another. Sometimes the letters appear "stuck," in that they do not fully return to baseline when transitioning from one to another. Like this:
![image](https://github.com/WinterCore/react-text-transition/assets/134559094/6de9718d-ce67-43cd-a2b4-d66020c4057d)
I've tried adjusting parameters of the animation and text styling, but the issue persists. Does anyone know how to prevent this from happening?

**Comment by Amatewasu** [comment]
@lukewhite9 I have the same issue. If you found something to fix it, i would be super happy if you could share it. Thanks a lot!
